// +build !stanfordrel

// Code generated by "stringer -type=DependencyType -output=dependencyType_universal_string.go"; DO NOT EDIT

package lingo

import "fmt"

const _DependencyType_name = "NoDepTypeDepRootNSubjNSubjPassDObjIObjCSubjCSubjPassCCompXCompNumModApposNModAClACl_RelClDetDet_PreDetAModNegCaseNMod_NPModNMod_TModNMod_PossAdvClAdvModCompoundCompound_PartNameMWEForeignGoesWithListDislocatedParataxisRemnantReparandumVocativeDiscourseExplAuxAuxPassCopMarkPunctConjCoordinationCC_PreConjMAXDEPTYPE"

var _DependencyType_index = [...]uint16{0, 9, 12, 16, 21, 30, 34, 38, 43, 52, 57, 62, 68, 73, 77, 80, 89, 92, 102, 106, 109, 113, 123, 132, 141, 146, 152, 160, 173, 177, 180, 187, 195, 199, 209, 218, 225, 235, 243, 252, 256, 259, 266, 269, 273, 278, 282, 294, 304, 314}

func (i DependencyType) String() string {
	if i >= DependencyType(len(_DependencyType_index)-1) {
		return fmt.Sprintf("DependencyType(%d)", i)
	}
	return _DependencyType_name[_DependencyType_index[i]:_DependencyType_index[i+1]]
}
