// Code generated by "stringer -type=LexemeType"; DO NOT EDIT

package lingo

import "fmt"

const _LexemeType_name = "EOFWordDisambigURINumberDateTimePunctuationSymbolSpaceSystemUse"

var _LexemeType_index = [...]uint8{0, 3, 7, 15, 18, 24, 28, 32, 43, 49, 54, 63}

func (i LexemeType) String() string {
	if i >= LexemeType(len(_LexemeType_index)-1) {
		return fmt.Sprintf("LexemeType(%d)", i)
	}
	return _LexemeType_name[_LexemeType_index[i]:_LexemeType_index[i+1]]
}
