// +build !stanfordtags

// Code generated by "stringer -type=POSTag -output=POSTag_universal_string.go"; DO NOT EDIT

package lingo

import "fmt"

const _POSTag_name = "XUNKNOWN_TAGROOT_TAGADJADPADVAUXCONJDETINTJNOUNNUMPARTPRONPROPNPUNCTSCONJSYMVERBMAXTAG"

var _POSTag_index = [...]uint8{0, 1, 12, 20, 23, 26, 29, 32, 36, 39, 43, 47, 50, 54, 58, 63, 68, 73, 76, 80, 86}

func (i POSTag) String() string {
	if i >= POSTag(len(_POSTag_index)-1) {
		return fmt.Sprintf("POSTag(%d)", i)
	}
	return _POSTag_name[_POSTag_index[i]:_POSTag_index[i+1]]
}
