// generated by stringer -type=contextType; DO NOT EDIT

package pos

import "fmt"

const _contextType_name = "prev2Wordprev2Lemmaprev2Clusterprev2Shapeprev2Prefix1prev2Suffix3prev2POSTagprev2FlagsprevWordprevLemmaprevClusterprevShapeprevPrefix1prevSuffix3prevPOSTagprevFlagsithWordithLemmaithClusterithShapeithPrefix1ithSuffix3ithPOSTagithFlagsnextWordnextLemmanextClusternextShapenextPrefix1nextSuffix3nextPOSTagnextFlagsnext2Wordnext2Lemmanext2Clusternext2Shapenext2Prefix1next2Suffix3next2POSTagnext2FlagsMAXCONTEXTTYPE"

var _contextType_index = [...]uint16{0, 9, 19, 31, 41, 53, 65, 76, 86, 94, 103, 114, 123, 134, 145, 155, 164, 171, 179, 189, 197, 207, 217, 226, 234, 242, 251, 262, 271, 282, 293, 303, 312, 321, 331, 343, 353, 365, 377, 388, 398, 412}

func (i contextType) String() string {
	if i >= contextType(len(_contextType_index)-1) {
		return fmt.Sprintf("contextType(%d)", i)
	}
	return _contextType_name[_contextType_index[i]:_contextType_index[i+1]]
}
