// generated by stringer -type=featureType; DO NOT EDIT

package pos

import "fmt"

const _featureType_name = "biasithWord_prevLemma_prevPOSTagprev2Lemma_prev2POSTagnextWord_next2Word_ithSuffix3_ithPrefix1_prevPOSTag_prev2POSTag_prevPOSTag_prev2_POSTagprevPOSTag_ithWordprevSuffix3_nextSuffix3_ithShape_ithCluster_nextCluster_next2Cluster_prevCluster_prev2Cluster_ithFlags_nextFlags_next2Flags_prevFlags_prev2Flags_MAXFEATURETYPE"

var _featureType_index = [...]uint16{0, 4, 12, 32, 54, 63, 73, 84, 95, 106, 118, 141, 159, 171, 183, 192, 203, 215, 228, 240, 253, 262, 272, 283, 293, 304, 318}

func (i featureType) String() string {
	if i >= featureType(len(_featureType_index)-1) {
		return fmt.Sprintf("featureType(%d)", i)
	}
	return _featureType_name[_featureType_index[i]:_featureType_index[i+1]]
}
